settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: bcn-plex # unique identifier
    name: Plex BCN
    description: 'Plex BCN' # default=empty
    url: 'http://segator.nodo.ovh:32400/' # URL to fetch
    method: GET # default=GET
    expectStatus: 401 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: bcn-stats # unique identifier
    name: Plex BCN Stats
    description: 'Plex BCN Stats' # default=empty
    url: 'https://stats-bcn.neries.li/auth/login' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  - id: bcn-plex # unique identifier
    name: Plex MAD
    description: 'Plex MAD' # default=empty
    url: 'http://jvdivx.synology.me:32400/' # URL to fetch
    method: GET # default=GET
    expectStatus: 401 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: mad-stats # unique identifier
    name: Plex Mad Stats
    description: 'Plex MAD Stats' # default=empty
    url: 'https://stats-mad.neries.li/auth/login' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  - id: tv # unique identifier
    name: TV
    description: 'TV' # default=empty
    url: 'https://tv.neries.li/login' # URL to fetch
    method: GET # default=GET
    expectStatus: 405 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: requests # unique identifier
    name: Plex Request Content
    description: 'Request Content' # default=empty
    url: 'https://request.neries.li/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

